apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail-daemonset
  annotations:
    reloader.stakater.com/search: "true"
spec:
  selector:
    matchLabels:
      name: promtail
  template:
    metadata:
      labels:
        name: promtail
    spec:
      serviceAccountName: promtail-sa
      containers:
      - name: promtail-cont
        image: grafana/promtail
        ports:
        - containerPort: 9080
        args:
        - -config.file=/etc/promtail/promtail-config.yml
        - -log.level=debug
        # - -config.expand-env=true
        volumeMounts:
        - name: varlog
          mountPath: /var/log/pods
          readOnly: true
        - name: container
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: promtail-config
          mountPath: /etc/promtail
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumes:
      - name: varlog
        hostPath:
          path: /var/log/pods
      - name: container
        hostPath:
          path: /var/lib/docker/containers
      - name: promtail-config
        configMap:
          name: promtail-config