apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail-sa

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promtail-crole

rules:
- apiGroups: [""]
  resources:
  - services
  - pods
  - nodes
  - nodes/proxy
  - endpoints
  verbs: ["get","list","watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promtail-crolebinding
subjects:
- kind: ServiceAccount
  name: promtail-sa
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: promtail-crole