---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: application
  name: logging-app
  labels:
    app: logging-app
    group: loki-test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: logging-app
      group: loki-test
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        name: logging-app
        group: loki-test
    spec:
      containers:
        - name: logging-app-container
          image: busybox
          args:
          - /bin/sh
          - -c
          -  while :; do echo "level=info this is a log message from loggy McLogface at $(date)"; sleep 5; done


