apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-grafana
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/grafana-data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-prometheus
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/prometheus-data"