apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics-service
  namespace: monitoring
spec:
  ports:
  - name: http-metrics
    port: 8080
    targetPort: 8080
  - name: telemetry
    port: 8081
    targetPort: 8080
  selector:
    name: kube-state-metrics
