apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
      - static_configs:
        - targets: []
    scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 15s
      static_configs:
      - targets: ['localhost:9090']
    - job_name: 'kube-state-metrics'
      scrape_interval: 15s
      static_configs:
      - targets: ['kube-state-metrics-service.monitoring.svc.cluster.local:8080']
